jobs: 
  notify: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Discord Webhook Notify"
        uses: rjstone/discord-webhook-notify@v1
        with: 
          description: "The modpack has been updated!"
          details: "Make sure to update your modpack by downloading the new instance export from here: https://github.com/unnamed-arma-group/UAGCraft/archive/release.zip"
          severity: info
          webhookUrl: "${{secrets.DISCORD_WEBHOOK}}"
name: CI
on: 
  release: 
    types: 
      - created
